steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/${_PROJECT_ID}/backend:${_SHORT_SHA}', '--build-arg', 'PORT=${_PORT}', '.']
  - name: gcr.io/cloud-builders/docker
    args: ['push', 'gcr.io/${_PROJECT_ID}/backend:${_SHORT_SHA}']
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    secretEnv: ['GROQ_MODEL', 'MODEL_TEMPERATURE', 'ALLOWED_ORIGINS']
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run deploy ${_PROJECT_ID}-backend \
          --image gcr.io/${_PROJECT_ID}/backend:${_SHORT_SHA} \
          --region asia-east1 \
          --allow-unauthenticated \
          --no-cpu-boost \
          --max-instances 1 \
          --set-env-vars GROQ_MODEL=$$GROQ_MODEL,MODEL_TEMPERATURE=$$MODEL_TEMPERATURE,ALLOWED_ORIGINS=$$ALLOWED_ORIGINS \
          --set-secrets GROQ_API_KEY=GROQ_API_KEY:latest
images:
  - gcr.io/${_PROJECT_ID}/backend:${_SHORT_SHA}
availableSecrets:
  secretManager:
    - env: GROQ_MODEL
      versionName: projects/${_PROJECT_ID}/secrets/GROQ_MODEL/versions/latest
    - env: MODEL_TEMPERATURE
      versionName: projects/${_PROJECT_ID}/secrets/MODEL_TEMPERATURE/versions/latest
    - env: ALLOWED_ORIGINS
      versionName: projects/${_PROJECT_ID}/secrets/ALLOWED_ORIGINS/versions/latest
